---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gs-spring-boot&var-version=0.1.0
  labels:
    provider: fabric8
    project: gs-spring-boot
    version: 0.1.0
    group: org.springframework
  name: gs-spring-boot
spec:
  replicas: 1
  selector:
    project: gs-spring-boot
    provider: fabric8
    group: org.springframework
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gs-spring-boot&var-version=0.1.0
      labels:
        provider: fabric8
        project: gs-spring-boot
        version: 0.1.0
        group: org.springframework
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        image: gs-spring-boot:0.1.0
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot
      from:
        kind: ImageStreamTag
        name: gs-spring-boot:0.1.0
    type: ImageChange
