---
apiVersion: v1
kind: ImageStream
metadata:
  name: gs-spring-boot
spec:
  tags:
  - from:
      kind: ImageStreamImage
      name: gs-spring-boot@sha256:2074a30a28853afe16479bb891517c2edacaa830cf39fff9aad0e3b1fe66cc16
      namespace: pru-development
    name: 0.1.0
