---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    provider: fabric8
    project: gs-spring-boot
    version: 0.1.0
    group: org.springframework
  name: gs-spring-boot
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: gs-spring-boot
    provider: fabric8
    group: org.springframework
  type: LoadBalancer
